spring.application.name=api

# This tells Spring exactly what the URL is
# Render gives us the environment variable DATABASE_URL
# We use this syntax to append the 'jdbc:' prefix
spring.datasource.url=jdbc:${DATABASE_URL}

# Important: Tell Spring to use the PostgreSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true